version: '3.9'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - kafka-network

  kafka1:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka2:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka2
    volumes:
      - ./data/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka3:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka3
    volumes:
      - ./data/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  redpanda-console:
    image: docker.redpanda.com/vectorized/console:latest
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka1:19091", "kafka2:19092", "kafka3:19093"]
          schemaRegistry:
            enabled: false
        redpanda:
          adminApi:
            enabled: false
        connect:
          enabled: true
          clusters:
            - name: kafka-connect
              url: http://kafka-connect:8083

    ports:
      - 8080:8080
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    networks:
      - kafka-network


  kafka-connect:
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    build: .
    container_name: kafka-connect
    hostname: kafka-connect
    environment:
        - CONNECT_BOOTSTRAP_SERVERS=kafka1:19091,kafka2:19092,kafka3:19093
        - CONNECT_GROUP_ID=kafcon3xx
        - CONNECT_CONFIG_STORAGE_TOPIC=_kafcon3xx-config
        - CONNECT_OFFSET_STORAGE_TOPIC=_kafcon3xx-offsets
        - CONNECT_STATUS_STORAGE_TOPIC=_kafcon3xx-status
        - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=3
        - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=3
        - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=3
        - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
        - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
        - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
        - CONNECT_PLUGIN_PATH=/usr/share/java

    ports:
        - 9099:19092
        - 8083:8083
    networks:
      - kafka-network

  arangodb_db_container:
    image: arangodb:latest
    container_name: arangodb
    depends_on:
      - kafka-connect
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
    networks:
      - kafka-network


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  arangodb_data_container:
    driver: local
  arangodb_apps_data_container:
    driver: local

networks:
  kafka-network:
    driver: bridge